# Generated from data/model.json model metadata.
# Do not edit this file directly; run scripts/generate-ml-model.mjs.
# Neural-network weights are compiled into the firmware by ML4F.
class MLModel
  LABELS = ["circle", "pose", "side", "up", "down"]
  LABEL_CIRCLE = 0
  LABEL_POSE = 1
  LABEL_SIDE = 2
  LABEL_UP = 3
  LABEL_DOWN = 4

  def evaluate(x_values, y_values, z_values)
    Microbit::ML.evaluate(
      x_values,
      y_values,
      z_values
    )
  end
end
