/*
 * Generated from examples/picoruby/magic-circle/data/model.json by
 * examples/picoruby/magic-circle/scripts/generate-ml4f-model.mjs.
 * Do not edit this file directly.
 *
 * SPDX-License-Identifier: MIT
 */

#pragma once

#define MBREMOTE_MAGIC_CIRCLE_MODEL_WORDS 744
#define MBREMOTE_MAGIC_CIRCLE_MODEL_ARENA_BYTES 168
#define MBREMOTE_MAGIC_CIRCLE_MODEL_OUTPUTS 5

extern const unsigned mbremote_magic_circle_model[
    MBREMOTE_MAGIC_CIRCLE_MODEL_WORDS
];
extern const float mbremote_magic_circle_required_confidence[
    MBREMOTE_MAGIC_CIRCLE_MODEL_OUTPUTS
];
extern const float mbremote_magic_circle_minimum_gesture_motion;
